logging:
  level:
    root: info
    com.example.aqxai: debug
spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: kohdirjob
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    path: /api-docs
key:
  for:
    Send:
      SMS: AccessKey xsTieTlZpZJjxyexNB2LK8PzJ
      Notification: AAAAxBapAx8:APA91bEEyEDsDsqPSgnQ5m7OkJKR9LUTRQarnfXH65KNUtuMX4NemaJDwgsOkhT9UKNTxd0fkYlWu7yAv6v8R7jBQc-x2bXrHpNBkQC2YwUy7VX885mpsLhZuosg_AvQTFN72LLrmnTC
