INSERT INTO regions (id, name_uz,name_ru) VALUES
                                              (1, 'Qoraqalpog‘iston Respublikasi','Қорақалпоғистон Республикаси'),
                                              (2, 'Andijon viloyati','Андижон вилояти'),
                                              (3, 'Buxoro viloyati','Бухоро вилояти'),
                                              (4, 'Jizzax viloyati','Жиззах вилояти'),
                                              (5, 'Qashqadaryo viloyati','Қашқадарё вилояти'),
                                              (6, 'Navoiy viloyati','Навоий вилояти'),
                                              (7, 'Namangan viloyati','Наманган вилояти'),
                                              (8, 'Samarqand viloyati','Самарқанд вилояти'),
                                              (9, 'Surxandaryo viloyati','Сурхандарё вилояти'),
                                              (10, 'Sirdaryo viloyati','Сирдарё вилояти'),
                                              (11, 'Toshkent viloyati','Тошкент вилояти'),
                                              (12, 'Farg‘ona viloyati','Фарғона вилояти'),
                                              (13, 'Xorazm viloyati','Хоразм вилояти'),
                                              (14, 'Toshkent shahri','Тошкент шаҳри');



INSERT INTO districts (id, region_id, name_uz,name_ru) VALUES

                                                           (15, 1, 'Amudaryo tumani','Амударё тумани'),
                                                           (16, 1, 'Beruniy tumani','Беруний тумани'),
                                                           (17, 1, 'Kegayli tumani','Кегайли тумани'),
                                                           (18, 1, 'Qonliko‘l tumani','Қонликўл тумани'),
                                                           (19, 1, 'Qorao‘zak tumani','Қораўзак тумани'),
                                                           (20, 1, 'Qo‘ng‘irot tumani','Қўнғирот тумани'),
                                                           (21, 1, 'Mo‘ynoq tumani','Мўйноқ тумани'),
                                                           (22, 1, 'Nukus tumani','Нукус тумани'),
                                                           (23, 1, 'Nukus shahri','Нукус шаҳри'),
                                                           (24, 1, 'Taxtako‘pir tumani','Тахтакўпир тумани'),
                                                           (25, 1, 'To‘rtko‘l tumani','Тўрткўл тумани'),
                                                           (26, 1, 'Xo‘jayli tumani','Хўжайли тумани'),
                                                           (27, 1, 'CHimboy tumani','Чимбой тумани'),
                                                           (28, 1, 'SHumanay tumani','Шуманай тумани'),
                                                           (29, 1, 'Ellikqal‘a tumani','Элликқал‘а тумани'),
                                                           (209, 1, 'Taxiatosh shahri','Тахиатош шаҳри'),

                                                           (30, 2, 'Andijon shahri','Андижон шаҳри'),
                                                           (31, 2, 'Andijon tumani','Андижон тумани'),
                                                           (32, 2, 'Asaka tumani','Асака тумани'),
                                                           (210, 2, 'Asaka shahri','Асака шаҳри'),
                                                           (33, 2, 'Baliqchi tumani','Балиқчи тумани'),
                                                           (34, 2, 'Buloqboshi tumani','Булоқбоши тумани'),
                                                           (35, 2, 'Bo‘z tumani','Бўз тумани'),
                                                           (36, 2, 'Jalaquduq tumani','Жалақудуқ тумани'),
                                                           (37, 2, 'Izbosgan tumani','Избосган тумани'),
                                                           (38, 2, 'Qorasuv shahri','Қорасув шаҳри'),
                                                           (39, 2, 'Qo‘rg‘ontepa tumani','Қўрғонтепа тумани'),
                                                           (40, 2, 'Marhamat tumani','Марҳамат тумани'),
                                                           (41, 2, 'Oltinko‘l tumani','Олтинкўл тумани'),
                                                           (42, 2, 'Paxtaobod tumani','Пахтаобод тумани'),
                                                           (43, 2, 'Ulug‘nor tumani','Улуғнор тумани'),
                                                           (44, 2, 'Xonabod tumani','Хонабод тумани'),
                                                           (45, 2, 'Xo‘jaobod shahri','Хўжаобод шаҳри'),
                                                           (46, 2, 'Shaxrixon tumani','Шахрихон тумани'),



                                                           (47, 3, 'Buxoro shahri','Бухоро шаҳри'),
                                                           (48, 3, 'Buxoro tumani','Бухоро тумани'),
                                                           (49, 3, 'Vobkent tumani','Вобкент тумани'),
                                                           (50, 3, 'G‘ijduvon tumani','Ғиждувон тумани'),
                                                           (51, 3, 'Jondor tumani','Жондор тумани'),
                                                           (52, 3, 'Kogon tumani','Когон тумани'),
                                                           (53, 3, 'Kogon shahri','Когон шаҳри'),
                                                           (54, 3, 'Qorako‘l tumani','Қоракўл тумани'),
                                                           (55, 3, 'Qorovulbozor tumani','Қоровулбозор тумани'),
                                                           (56, 3, 'Olot tumani','Олот тумани'),
                                                           (57, 3, 'Peshku tumani','Пешку тумани'),
                                                           (58, 3, 'Romitan tumani','Ромитан тумани'),
                                                           (59, 3, 'Shofirkon tumani','Шофиркон тумани'),

                                                           (60, 4, 'Arnasoy tumani','Арнасой тумани'),
                                                           (61, 4, 'Baxmal tumani','Бахмал тумани'),
                                                           (62, 4, 'G‘allaorol tumani','Ғаллаорол тумани'),
                                                           (63, 4, 'Do‘stlik tumani','Дўстлик тумани'),
                                                           (64, 4, 'Sh.Rashidov tumani','ъШ.ашидов тумани'),
                                                           (65, 4, 'Jizzax shahri','Жиззах шаҳри'),
                                                           (66, 4, 'Zarbdor tumani','Зарбдор тумани'),
                                                           (67, 4, 'Zafarobod tumani','Зафаробод тумани'),
                                                           (68, 4, 'Zomin tumani','Зомин тумани'),
                                                           (69, 4, 'Mirzacho‘l tumani','Мирзачўл тумани'),
                                                           (70, 4, 'Paxtakor tumani','Пахтакор тумани'),
                                                           (71, 4, 'Forish tumani','Фориш тумани'),
                                                           (72, 4, 'Yangiobod tumani','Янгиобод тумани'),



                                                           (73, 5, 'G‘uzor tumani','Ғузор тумани'),
                                                           (74, 5, 'Dehqonobod tumani','Деҳқонобод тумани'),
                                                           (75, 5, 'Qamashi tumani','Қамаши тумани'),
                                                           (76, 5, 'Qarshi tumani','Қарши тумани'),
                                                           (77, 5, 'Qarshi shahri','Қарши шаҳри'),
                                                           (78, 5, 'Kasbi tumani','Касби тумани'),
                                                           (79, 5, 'Kitob tumani','Китоб тумани'),
                                                           (80, 5, 'Koson tumani','Косон тумани'),
                                                           (81, 5, 'Mirishkor tumani','Миришкор тумани'),
                                                           (82, 5, 'Muborak tumani','Муборак тумани'),
                                                           (83, 5, 'Nishon tumani','Нишон тумани'),
                                                           (84, 5, 'Chiroqchi tumani','Чироқчи тумани'),
                                                           (85, 5, 'Shahrisabz tumani','Шаҳрисабз тумани'),
                                                           (86, 5, 'Yakkabog‘ tumani','Яккабоғ тумани'),
                                                           (87, 6, 'Zarafshon shahri','Зарафшон шаҳри'),
                                                           (88, 6, 'Karmana tumani','Кармана тумани'),
                                                           (89, 6, 'Qiziltepa tumani','Қизилтепа тумани'),
                                                           (90, 6, 'Konimex tumani','Конимех тумани'),
                                                           (91, 6, 'Navbahor tumani','Навбаҳор тумани'),
                                                           (92, 6, 'Navoiy shahri','Навоий шаҳри'),
                                                           (93, 6, 'Nurota tumani','Нурота тумани'),
                                                           (94, 6, 'Tomdi tumani','Томди тумани'),
                                                           (95, 6, 'Uchquduq tumani','Учқудуқ тумани'),
                                                           (96, 6, 'Xatirchi tumani','Хатирчи тумани'),

                                                           (97, 7, 'Kosonsoy tumani','Косонсой тумани'),
                                                           (98, 7, 'Mingbuloq tumani','Мингбулоқ тумани'),
                                                           (99, 7, 'Namangan tumani','Наманган тумани'),
                                                           (100, 7, 'Namangan shahri','Наманган шаҳри'),
                                                           (101, 7, 'Norin tumani','Норин тумани'),
                                                           (102, 7, 'Pop tumani','Поп тумани'),
                                                           (103, 7, 'To‘raqo‘rg‘on tumani','Тўрақўрғон тумани'),
                                                           (104, 7, 'Uychi tumani','Уйчи тумани'),
                                                           (105, 7, 'Uchqo‘rg‘on tumani','Учқўрғон тумани'),
                                                           (106, 7, 'Chortoq tumani','Чортоқ тумани'),
                                                           (107, 7, 'Chust tumani','Чуст тумани'),
                                                           (108, 7, 'Yangiqo‘rg‘on tumani','Янгиқўрғон тумани'),

                                                           (109, 8, 'Bulung‘ur tumani','Булунғур тумани'),
                                                           (110, 8, 'Jomboy tumani','Жомбой тумани'),
                                                           (111, 8, 'Ishtixon tumani','Иштихон тумани'),
                                                           (112, 8, 'Kattaqo‘rg‘on tumani','Каттақўрғон тумани'),
                                                           (113, 8, 'Kattaqo‘rg‘on shahri','Каттақўрғон шаҳри'),
                                                           (114, 8, 'Qo‘shrabot tumani','Қўшработ тумани'),
                                                           (115, 8, 'Narpay tumani','Нарпай тумани'),
                                                           (116, 8, 'Nurabod tumani','Нурабод тумани'),
                                                           (117, 8, 'Oqdaryo tumani','Оқдарё тумани'),
                                                           (118, 8, 'Payariq tumani','Паяриқ тумани'),
                                                           (119, 8, 'Pastarg‘om tumani','Пастарғом тумани'),
                                                           (120, 8, 'Paxtachi tumani','Пахтачи тумани'),
                                                           (121, 8, 'Samarqand tumani','Самарқанд тумани'),
                                                           (122, 8, 'Samarqand shahri','Самарқанд шаҳри'),
                                                           (123, 8, 'Toyloq tumani','Тойлоқ тумани'),
                                                           (124, 8, 'Urgut tumani','Ургут тумани'),

                                                           (125, 9, 'Angor tumani','Ангор тумани'),
                                                           (126, 9, 'Boysun tumani','Бойсун тумани'),
                                                           (127, 9, 'Denov tumani','Денов тумани'),
                                                           (128, 9, 'Jarqo‘rg‘on tumani','Жарқўрғон тумани'),
                                                           (129, 9, 'Qiziriq tumani','Қизириқ тумани'),
                                                           (130, 9, 'Qo‘mqo‘rg‘on tumani','Қўмқўрғон тумани'),
                                                           (131, 9, 'Muzrabot tumani','Музработ тумани'),
                                                           (132, 9, 'Oltinsoy tumani','Олтинсой тумани'),
                                                           (133, 9, 'Sariosiy tumani','Сариосий тумани'),
                                                           (134, 9, 'Termiz tumani','Термиз тумани'),
                                                           (135, 9, 'Termiz shahri','Термиз шаҳри'),
                                                           (136, 9, 'Uzun tumani','Узун тумани'),
                                                           (137, 9, 'Sherobod tumani','Шеробод тумани'),
                                                           (138, 9, 'Sho‘rchi tumani','Шўрчи тумани'),
                                                           (211, 9, 'Bandixon tumani','Бандихон тумани'),

                                                           (139, 10, 'Boyovut tumani','Боёвут тумани'),
                                                           (140, 10, 'Guliston tumani','Гулистон тумани'),
                                                           (141, 10, 'Guliston shahri','Гулистон шаҳри'),
                                                           (142, 10, 'Mirzaobod tumani','Мирзаобод тумани'),
                                                           (143, 10, 'Oqoltin tumani','Оқолтин тумани'),
                                                           (144, 10, 'Sayxunobod tumani','Сайхунобод тумани'),
                                                           (145, 10, 'Sardoba tumani','Сардоба тумани'),
                                                           (146, 10, 'Sirdaryo tumani','Сирдарё тумани'),
                                                           (147, 10, 'Xavos tumani','Хавос тумани'),
                                                           (148, 10, 'Shirin shahri','Ширин шаҳри'),
                                                           (149, 10, 'Yangier shahri','Янгиер шаҳри'),

                                                           (150, 11, 'Angiren shahri','Ангирен шаҳри'),
                                                           (151, 11, 'Bekabod tumani','Бекабод тумани'),
                                                           (152, 11, 'Bekabod shahri','Бекабод шаҳри'),
                                                           (153, 11, 'Bo‘ka tumani','Бўка тумани'),
                                                           (154, 11, 'Bo‘stonliq tumani','Бўстонлиқ тумани'),
                                                           (155, 11, 'Zangiota tumani','Зангиота тумани'),
                                                           (156, 11, 'Qibray tumani','Қибрай тумани'),
                                                           (157, 11, 'Quyichirchiq tumani','Қуйичирчиқ тумани'),
                                                           (158, 11, 'Oqqo‘rg‘on tumani','Оққўрғон тумани'),
                                                           (159, 11, 'Olmaliq shahri','Олмалиқ шаҳри'),
                                                           (160, 11, 'Ohangaron tumani','Оҳангарон тумани'),
                                                           (161, 11, 'Parkent tumani','Паркент тумани'),
                                                           (162, 11, 'Piskent tumani','Пискент тумани'),
                                                           (163, 11, 'O‘rtachirchiq tumani','Ўртачирчиқ тумани'),
                                                           (164, 11, 'Chinoz tumani','Чиноз тумани'),
                                                           (165, 11, 'Chirchiq shahri','Чирчиқ шаҳри'),
                                                           (166, 11, 'Yuqorichirchiq tumani','Юқоричирчиқ тумани'),
                                                           (212, 11, 'Ohangaron shahri','Оҳангарон шаҳри'),
                                                           (213, 11, 'Yangiyo‘l shahri','Янгиёл шаҳри'),
                                                           (215, 11, 'Toshkent tumani','Тошкент тумани'),

                                                           (167, 11, 'Yangiyo‘l tumani','Янгиё‘л тумани'),
                                                           (168, 12, 'Beshariq tumani','Бешариқ тумани'),
                                                           (169, 12, 'Bog‘dod tumani','Боғдод тумани'),
                                                           (170, 12, 'Buvayda tumani','Бувайда тумани'),
                                                           (171, 12, 'Dang‘ara tumani','Данғара тумани'),
                                                           (172, 12, 'Yozyovon tumani','Ёзёвон тумани'),
                                                           (173, 12, 'Quva tumani','Қува тумани'),
                                                           (174, 12, 'Quvasoy shahri','Қувасой шаҳри'),
                                                           (175, 12, 'Qo‘qon shahri','Қўқон шаҳри'),
                                                           (176, 12, 'Qo‘shtepa tumani','Қўштепа тумани'),
                                                           (177, 12, 'Marg‘ilon shahri','Марғилон шаҳри'),
                                                           (178, 12, 'Oltiariq tumani','Олтиариқ тумани'),
                                                           (179, 12, 'Rishton tumani','Риштон тумани'),
                                                           (180, 12, 'So‘x tumani','Сўх тумани'),
                                                           (181, 12, 'Toshloq tumani','Тошлоқ тумани'),
                                                           (182, 12, 'Uchko‘prik tumani','Учкўприк тумани'),
                                                           (183, 12, 'O‘zbekiston tumani','Ўзбекистон тумани'),
                                                           (184, 12, 'Farg‘ona tumani','Фарғона тумани'),
                                                           (185, 12, 'Farg‘ona shahri','Фарғона шаҳри'),
                                                           (186, 12, 'Furqat tumani','Фурқат тумани'),

                                                           (187, 13, 'Bog‘ot tumani','Боғот тумани'),
                                                           (188, 13, 'Gurlan tumani','Гурлан тумани'),
                                                           (189, 13, 'Qo‘shko‘pir tumani','Қўшкўпир тумани'),
                                                           (190, 13, 'Urganch tumani','Урганч тумани'),
                                                           (191, 13, 'Urganch shahri','Урганч шаҳри'),
                                                           (192, 13, 'Xiva tumani','Хива тумани'),
                                                           (193, 13, 'Xazarasp tumani','Хазарасп тумани'),
                                                           (194, 13, 'Xonqa tumani','Хонқа тумани'),
                                                           (195, 13, 'Shavot tumani','Шавот тумани'),
                                                           (196, 13, 'Yangiariq tumani','Янгиариқ тумани'),
                                                           (197, 13, 'Yangibozor tumani','Янгибозор тумани'),

                                                           (198, 14, 'Bektimer tumani','Бектимер тумани'),
                                                           (199, 14, 'M.Ulug‘bek tumani','М.Улуғбек тумани'),
                                                           (200, 14, 'Mirobod tumani','Миробод тумани'),
                                                           (201, 14, 'Olmazor tumani','Олмазор тумани'),
                                                           (202, 14, 'Sergeli tumani','Сергели тумани'),
                                                           (203, 14, 'Uchtepa tumani','Учтепа тумани'),
                                                           (204, 14, 'Yashnobod tumani','Яшнобод тумани'),
                                                           (205, 14, 'Chilonzor tumani','Чилонзор тумани'),
                                                           (206, 14, 'Shayxontohur tumani','Шайхонтоҳур тумани'),
                                                           (207, 14, 'Yunusobod tumani','Юнусобод тумани'),
                                                           (208, 14, 'Yakkasaroy tumani','Яккасарой тумани');